### ISSUE TITLE
it says my wifi name in not defined. 

### ISSUE THREAD

**Issue by ItsBullDr** [vanquisher2122/Wifi-cracker#1]
after running the wifiC.py it asks me to insert ssid. i put my wifi name and it doesnt work. i tried different wifi
[*] SSID: A02-RA145-W300N                                                    
Traceback (most recent call last):                                           
  File "wifiC.py", line 119, in <module>                                     
    menu()                                                                   
  File "wifiC.py", line 100, in menu                                         
    ssid = input("[*] SSID: ")                                               
  File "<string>", line 1, in <module>                                       
NameError: name 'A02' is not defined 

EDIT:
after putting my wifi name with "" it worked but now after i did everything it says this. im not very expert so i dont know what is it
('\x1b[1;34m', '[~] Cracking...')                                            
Traceback (most recent call last):                                           
  File "wifiC.py", line 119, in <module>                                     
    menu()                                                                   
  File "wifiC.py", line 112, in menu                                         
    pwd(ssid, filee)                                                         
  File "wifiC.py", line 68, in pwd                                           
    with open(file, 'r', encoding='utf8') as words:                          
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by skee21** [comment]
Can you please attach a screen recording, or explain the error in brief?

And sorry for late reply...

**Comment by ItsBullDr** [comment]
> Can you please attach a screen recording, or explain the error in brief? And sorry for late reply...
> […](#)

Here’s the vid. Sorry I didn’t see the reply earlier. Maybe it’s something wrong I did. I’m new to this kind of stuff
https://drive.google.com/file/d/1l00P0SJYU3Ur7yrLSDInIATHsOjlNZG0/view?usp=drivesdk

**Comment by vanquisher2122** [comment]
Sorry for the late I was busy with another stuffs, the error you're showing is most likely resolved, I'd like you to update the programme with the new one. Please download the WifiC file again and run, it should work!!
Have a great day!!

**Comment by skee21** [comment]
Sorry for the late I was busy with another stuffs. 
The error you're showing is most likely resolved, I'd like you to update the programme with the new one. Please download the WifiC file again and run, it should work!!
Have a great day!!
